# Generated by Django 5.0.2 on 2024-03-15 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('clothes', 'Clothes'), ('footwear', 'Footwear'), ('jewerly', 'Jewerly'), ('perfume', 'Perfume'), ('cosmetics', 'Cosmetics'), ('glasses', 'Glasses'), ('bags', 'Bags')], default='clothes', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.TextField(default='Non définie')),
                ('prix', models.DecimalField(decimal_places=3, max_digits=10)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('imgH', models.ImageField(blank=True, upload_to='')),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.categorie')),
            ],
        ),
    ]
