# Generated by Django 5.0.2 on 2024-04-23 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
