# Generated by Django 5.0.2 on 2024-05-06 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_alter_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
