# Generated by Django 5.0.2 on 2024-02-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0004_alter_categorie_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='name',
            field=models.CharField(default='Alimentaire', max_length=50),
        ),
    ]
