# Generated by Django 5.0.2 on 2024-02-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0006_fournisseur_produitnc_alter_categorie_name_commandes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='name',
            field=models.CharField(choices=[('Al', 'Alimentaire'), ('Mb', 'Meuble'), ('Sn', 'Sanitaire'), ('Vs', 'Vaisselle'), ('Vt', 'Vêtement'), ('Jx', 'Jouets'), ('Lg', 'Linge de Maison'), ('Bj', 'Bijoux'), ('Dc', 'Décor'), ('Im', 'Immobilier'), ('M', 'Meuble'), ('V', 'Vêtement'), ('L', 'Linge'), ('Para', 'ParaPharmacie'), ('E', 'Electroménager'), ('T', 'Tapis'), ('F', 'Frais')], default='Alimentaire', max_length=50),
        ),
    ]
