# Generated by Django 5.0.2 on 2024-03-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0007_alter_categorie_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='name',
            field=models.CharField(choices=[('Clothes', 'Clothes'), ('Footwear', 'Footwear'), ('Jewerly', 'Jewerly'), ('Perfume', 'Perfume'), ('Cosmetics', 'Cosmetics'), ('Glasses', 'Glasses'), ('Bags', 'Bags')], default='Alimentaire', max_length=50),
        ),
    ]
