# Generated by Django 5.0.2 on 2024-03-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0009_remove_produit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='imgH',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
